const projectPreview = (fileName) => `${import.meta.env.BASE_URL}projects/${fileName}`;

const worksProjects = [
  {
    id: 1,
    tab: "TRADING",
    title: "Antry",
    period: "2026.06.19 - 2026.07.24",
    projectType: "Team Project",
    summary: "실시간 주식·가상자산 시장 데이터를 한 화면에서 확인하고, AI 분석과 예측 신호를 바탕으로 사용자의 빠르고 안전한 의사결정을 지원하는 트레이딩 보조 서비스입니다.",
    implementation: "React로 대시보드를 구성하고 Flask API를 통해 시장 데이터와 분석 결과를 연결했으며, LangChain 기반 챗봇과 LightGBM 예측 모델을 결합해 투자 판단에 필요한 정보를 제공하도록 구현했습니다.",
    tags: ["React", "Flask", "LangChain", "Supabase", "LightGBM", "Docker", "AWS", "Vercel"],
    sourceUrl: "https://github.com/iensud184-max/Trading",
    pdfUrl: "https://github.com/iensud184-max/Trading/blob/main/ANTRY-AI-Trading-Platform.pdf",
    liveLinks: [{ label: "TRADING APP", url: "https://trading-lake-ten.vercel.app/" }],
    previewImage: projectPreview("trading.png"),
    previewAlt: "AI Trading Assistant dashboard preview",
  },
  {
    id: 2,
    tab: "SUBWAY",
    title: "지하철 혼잡도 분석",
    period: "2026.05.21 - 2026.06.12",
    projectType: "Team Project",
    summary: "실시간 열차 위치와 승객 수요 데이터를 분석해 혼잡도를 예측하고, 노선별 이동 흐름을 직관적으로 확인할 수 있도록 구현한 대시보드입니다.",
    implementation: "Pandas로 지하철 데이터를 전처리하고 LSTM 모델로 혼잡도를 예측했으며, Streamlit과 Plotly를 활용해 예측 결과와 노선별 이동 흐름을 시각화했습니다.",
    tags: ["Streamlit", "Plotly", "LSTM", "Pandas", "scikit-learn"],
    sourceUrl: "https://github.com/Decaf-subway/subway-line2",
    pdfUrl: "https://github.com/Decaf-subway/subway-line2/blob/main/DeCafe_Subway.pdf",
    liveLinks: [
      { label: "SUBWAY LINE 2", url: "https://huggingface.co/spaces/lololoooool/subway_line2" },
      { label: "SUBWAY LINE 1-8", url: "https://huggingface.co/spaces/lololoooool/subway_line1_8" },
    ],
    previewImage: projectPreview("subway.png"),
    previewAlt: "Seoul Subway Line 2 dashboard preview",
  },
  {
    id: 3,
    tab: "MOVIE",
    title: "FilmAtique",
    period: "2026.04.06 - 2026.04.29",
    projectType: "Team Project",
    summary: "영화 예매부터 결제, 회원 관리와 관리자 기능까지 영화관 서비스의 주요 흐름을 구현한 팀 프로젝트입니다.",
    implementation: "Flask와 MySQL을 기반으로 영화·예매·회원 데이터를 관리하고, SQLAlchemy ORM으로 데이터베이스를 연동했으며 결제 기능과 관리자 페이지를 구현했습니다.",
    tags: ["Python", "Flask", "SQLAlchemy", "MySQL", "Jinja2", "Bootstrap", "Toss Payments"],
    sourceUrl: "https://github.com/iensud184-max/movie_260407",
    pdfUrl: "https://github.com/iensud184-max/movie_260407/blob/main/Filmatique.pdf",
    liveLinks: [{ label: "FILMATIQUE", url: "https://filmatique.onrender.com" }],
    previewImage: projectPreview("movie.png"),
    previewAlt: "Filmatique cinema site preview",
  },
  {
    id: 4,
    tab: "KYOBO",
    title: "Kyobo Book",
    period: "2026.03.16 - 2026.04.02",
    projectType: "Personal Project",
    summary: "HTML, CSS, JavaScript를 처음 학습하며 웹페이지의 구조와 스타일, 기본 인터랙션을 직접 구현해 본 첫 웹 프로젝트입니다.",
    implementation: "교보문고 메인 페이지를 참고해 네비게이션, 배너 슬라이드, 상품 영역을 구성했으며 Swiper와 JavaScript를 활용해 기본적인 사용자 인터랙션을 구현했습니다.",
    tags: ["HTML5", "CSS3", "JavaScript", "Swiper", "Font Awesome"],
    sourceUrl: "https://github.com/iensud184-max/KDH_project1_kyobobook",
    pdfUrl: "https://github.com/iensud184-max/KDH_project1_kyobobook/blob/main/project1_portfolio.pdf",
    liveLinks: [{ label: "KYOBO BOOK", url: "https://iensud184-max.github.io/KDH_project1_kyobobook/" }],
    previewImage: projectPreview("kyobo.png"),
    previewAlt: "Kyobo Book storefront preview",
  },
];

export default worksProjects;
