const worksProjects = [
  {
    id: 1,
    tab: "TRADING",
    title: "Antry",
    period: "2026.06.19 - 2026.07.24",
    summary: "복잡한 시장 정보를 직관적으로 보여주고, AI 분석 결과를 활용해 빠른 의사결정을 지원하는 트레이딩 서비스입니다.",
    tags: ["React 19", "Tailwind CSS", "Vite", "Flask", "Supabase", "PostgreSQL", "LightGBM", "TradingView"],
    sourceUrl: "https://github.com/iensud184-max/Trading",
    liveLinks: [{ label: "TRADING APP", url: "https://trading-lake-ten.vercel.app/" }],
    previewImage: "/projects/trading.png",
    previewAlt: "AI Trading Assistant dashboard preview",
  },
  {
    id: 2,
    tab: "SUBWAY",
    title: "지하철 혼잡도 분석",
    period: "2026.05.21 - 2026.06.12",
    summary: "실시간 열차 위치와 승객 수요 데이터를 분석해 혼잡도를 예측하고, 노선별 이동 흐름을 직관적으로 확인할 수 있도록 구현한 대시보드입니다.",
    tags: ["Streamlit", "Plotly", "Pandas", "TensorFlow", "scikit-learn", "XGBoost", "LightGBM", "Docker"],
    sourceUrl: "https://github.com/Decaf-subway/subway-line2",
    liveLinks: [
      { label: "SUBWAY LINE 2", url: "https://huggingface.co/spaces/lololoooool/subway_line2" },
      { label: "SUBWAY LINE 1-8", url: "https://huggingface.co/spaces/lololoooool/subway_line1_8" },
    ],
    previewImage: "/projects/subway.png",
    previewAlt: "Seoul Subway Line 2 dashboard preview",
  },
  {
    id: 3,
    tab: "MOVIE",
    title: "FilmAtique",
    period: "2026.04.06 - 2026.04.29",
    summary: "영화 예매부터 결제, 회원 관리와 관리자 기능까지 영화관 서비스의 주요 흐름을 구현한 팀 프로젝트입니다.",
    tags: ["Python", "Flask", "SQLAlchemy", "MySQL", "Jinja2", "Bootstrap", "Toss Payments"],
    sourceUrl: "https://github.com/iensud184-max/movie_260407",
    liveLinks: [{ label: "FILMATIQUE", url: "https://hub.docker.com/r/kangminsik/filmatique" }],
    previewImage: "/projects/movie.png",
    previewAlt: "Filmatique cinema site preview",
  },
  {
    id: 4,
    tab: "KYOBO",
    title: "Kyobo Book",
    period: "2026.03.16 - 2026.04.02",
    summary: "HTML, CSS, JavaScript를 처음 학습하며 웹페이지의 구조와 스타일, 기본 인터랙션을 직접 구현해 본 첫 웹 프로젝트입니다.",
    tags: ["HTML5", "CSS3", "JavaScript", "Swiper", "Font Awesome"],
    sourceUrl: "https://github.com/iensud184-max/KDH_project1_kyobobook",
    liveLinks: [{ label: "KYOBO BOOK", url: "https://iensud184-max.github.io/KDH_project1_kyobobook/" }],
    previewImage: "/projects/kyobo.png",
    previewAlt: "Kyobo Book storefront preview",
  },
];

export default worksProjects;
